SELECT * FROM public.customer_data;

-- Q1) What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer_data
group by gender;

-- Q2) Which customers used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount
from customer_data
where discount_applied = 'Yes' and purchase_amount >=
(select AVG(purchase_amount) from customer_data)
;

-- Q3) Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),2) as avg_rating
from customer_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5
;

-- Q4) Compare the average purchase amount between standard and express shipping

select shipping_type,ROUND(AVG(purchase_amount::NUMERIC),2) as avg_amount
from customer_data
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type
;


-- Q5)  Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers

select subscription_status,
COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_amount,
SUM(purchase_amount) as total_revenue
FROM customer_data
GROUP BY subscription_status
;

-- q6) which 5 products has the highest percentage of purchased with the discount applied?

select item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100/COUNT(*) ,2) as discount_rate
from customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5
;

-- Q7) Segment customers into New, Returning and loyal based on their total 
-- number of previous purchases, and show the count of each segment

SELECT Max(previous_purchases),MIN(previous_purchases),ROUND(AVG(previous_purchases),2)
FROM customer_data 
;


with customer_type as
(SELECT customer_id, 
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END as customer_segment
FROM customer_data)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC
;

-- Q8) What are the top 3 most purchased product within each category?

SELECT category, count(*)
FROM customer_data
group by category;

with itemcounts as
(SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as orderof
FROM customer_data
GROUP BY category,item_purchased
)
SELECT orderof,category,item_purchased,total_orders
FROM itemcounts
WHERE orderof <= 3
;

-- Q9) Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe ?

SELECT subscription_status,
COUNT(customer_id) as reapeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status
;

-- q10) What is the revenue contribution of each age group?

SELECT age_group, 
SUM(purchase_amount) as revenue
FROM customer_data
GROUP BY age_group
ORDER BY revenue DESC
;

SELECT *
FROM customer_data 
WHERE gender = 'Female'
AND subscription_status = 'Yes'
;
